function init(self)
	msg.post(".", "acquire_input_focus")

	self.collision_id = nil     
	self.dragged_id = nil       
	self.dragged_pos = nil		
	self.pressed = false		
end

function update(self, dt)
	local pos = go.get_position()

	self.collision_id = nil
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		if not self.collision_id or
		go.get_position(self.collision_id).z < message.other_position.z then
			self.collision_id = message.other_id
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then

		local action_pos = vmath.vector3(action.x, action.y, 1)
		go.set_position(action_pos)

		if action.pressed then
			msg.post("cards1#cards", "itemPressed")
			self.pressed = true

		elseif action.released then
			msg.post("cards1#cards", "itemReleased")
			self.pressed = false
			self.dragged_id = nil
			self.dragging = false
			
			local s1 = vmath.vector3(1.0, 1.0, 1.0)
			go.set_scale(s1, self.collision_id)
		end

		if self.pressed and self.collision_id and not self.dragged_id then
			self.dragged_id = self.collision_id
			self.dragged_pos = action_pos

			local s2 = vmath.vector3(1.2, 1.2, 1.0)
			go.set_scale(s2, self.collision_id)
		end

		if self.dragged_id and vmath.length(self.dragged_pos - action_pos) > 5 then
			self.dragging = true
		end

		if self.dragging then
			go.set_position(action_pos, self.dragged_id)
		end
	end
end